# Generated by Django 3.0 on 2021-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210324_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageURL',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
