# Generated by Django 3.0 on 2021-03-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipe_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageURL',
            field=models.ImageField(upload_to=''),
        ),
    ]
