# Generated by Django 3.0 on 2021-03-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210325_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageURL',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
