# Generated by Django 3.0 on 2021-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210325_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
