# Generated by Django 3.0 on 2021-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210325_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageURL',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
