# Generated by Django 3.0 on 2021-03-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210325_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='imageURL',
        ),
    ]
